//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikroblog.videos_designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mikroblog.videos_designer.src.Util.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Video.
        /// </summary>
        public static string ButtonContentCreateVideo {
            get {
                return ResourceManager.GetString("ButtonContentCreateVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Designer Mode.
        /// </summary>
        public static string ButtonContentDisableDesignerMode {
            get {
                return ResourceManager.GetString("ButtonContentDisableDesignerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Text Edit Mode.
        /// </summary>
        public static string ButtonContentDisableTextEditMode {
            get {
                return ResourceManager.GetString("ButtonContentDisableTextEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Discussion.
        /// </summary>
        public static string ButtonContentDropDiscussion {
            get {
                return ResourceManager.GetString("ButtonContentDropDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Designer Mode.
        /// </summary>
        public static string ButtonContentEnableDesignerMode {
            get {
                return ResourceManager.GetString("ButtonContentEnableDesignerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Text Edit Mode.
        /// </summary>
        public static string ButtonContentEnableTextEditMode {
            get {
                return ResourceManager.GetString("ButtonContentEnableTextEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string ButtonContentNextDiscussion {
            get {
                return ResourceManager.GetString("ButtonContentNextDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Speech.
        /// </summary>
        public static string ButtonContentPlaySpeech {
            get {
                return ResourceManager.GetString("ButtonContentPlaySpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Video.
        /// </summary>
        public static string ButtonContentPlayVideo {
            get {
                return ResourceManager.GetString("ButtonContentPlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string ButtonContentPreviousDiscussion {
            get {
                return ResourceManager.GetString("ButtonContentPreviousDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Discussion Files.
        /// </summary>
        public static string ButtonContentRemoveDiscussionFiles {
            get {
                return ResourceManager.GetString("ButtonContentRemoveDiscussionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string ButtonContentScreenshot {
            get {
                return ResourceManager.GetString("ButtonContentScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot All.
        /// </summary>
        public static string ButtonContentScreenshotAll {
            get {
                return ResourceManager.GetString("ButtonContentScreenshotAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot and Speak.
        /// </summary>
        public static string ButtonContentScreenshotSpeak {
            get {
                return ResourceManager.GetString("ButtonContentScreenshotSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot and Speak All.
        /// </summary>
        public static string ButtonContentScreenshotSpeakAll {
            get {
                return ResourceManager.GetString("ButtonContentScreenshotSpeakAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        public static string ButtonContentSpeak {
            get {
                return ResourceManager.GetString("ButtonContentSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak All.
        /// </summary>
        public static string ButtonContentSpeakAll {
            get {
                return ResourceManager.GetString("ButtonContentSpeakAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Speech.
        /// </summary>
        public static string ButtonContentStopSpeech {
            get {
                return ResourceManager.GetString("ButtonContentStopSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Video.
        /// </summary>
        public static string ButtonContentStopVideo {
            get {
                return ResourceManager.GetString("ButtonContentStopVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion ID: .
        /// </summary>
        public static string LabelDiscussionId {
            get {
                return ResourceManager.GetString("LabelDiscussionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion: .
        /// </summary>
        public static string LabelDiscussionNumber {
            get {
                return ResourceManager.GetString("LabelDiscussionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality: .
        /// </summary>
        public static string LabelDiscussionQuality {
            get {
                return ResourceManager.GetString("LabelDiscussionQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing files in the discussion folder, do you want to remove them?.
        /// </summary>
        public static string LabelExistingDiscussionFiles {
            get {
                return ResourceManager.GetString("LabelExistingDiscussionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Length.
        /// </summary>
        public static string LabelSpeechLength {
            get {
                return ResourceManager.GetString("LabelSpeechLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Designer.
        /// </summary>
        public static string LabelVideoDesigner {
            get {
                return ResourceManager.GetString("LabelVideoDesigner", resourceCulture);
            }
        }
    }
}
